networks:
  dokploy-network:
    external: true   # use o nome exato listado no 'docker network ls'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-app
    restart: always
    expose:
      - "80"           # visível na rede docker para o Traefik
    ports:
      - "8081:80"      # você mantém o acesso direto via IP:8081
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/"]
      interval: 10s
      timeout: 3s
      retries: 5
    
    labels:
      - traefik.enable=true
      - traefik.http.routers.rmtpark-frontend-4dolk1.rule=Host(`front.rmtpark.com`)
      - traefik.http.routers.rmtpark-frontend-4dolk1.entrypoints=web
      - traefik.http.services.rmtpark-frontend-4dolk1.loadbalancer.server.port=8081